### ISSUE TITLE
JavaScript error when running the first Sample App

### ISSUE THREAD

**Issue by chosenken** [LeviBotelho/LearnAngular#6]
When I attempt to run the first sample app, I am getting the following javascript error:

```
Error: Blocked a frame with origin "http://www.learn-angular.org" from accessing a cross-origin frame.
    at Error (native)
    at h.n.run (http://www.learn-angular.org/bundles/scripts?v=f0y9mqEfGJgi7v47CYJOTsTHeGJYfrd2tWBpTm54HXg1:1:1741)
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.2.12/angular.min.js:163:57
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.2.12/angular.min.js:179:344
    at h.$eval (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.12/angular.min.js:102:456)
    at h.$apply (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.12/angular.min.js:103:212)
    at HTMLButtonElement.<anonymous> (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.12/angular.min.js:179:326)
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.2.12/angular.min.js:27:208
    at q (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.12/angular.min.js:7:386)
    at HTMLButtonElement.Yc.c (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.12/angular.min.js:27:190) angular.js:9435
(anonymous function) angular.js:9435
(anonymous function) angular.js:6846
h.$apply angular.js:12079
(anonymous function) angular.js:18002
(anonymous function) angular.js:2616
q angular.js:310
Yc.c angular.js:2615
```

I am using Chrome on Mac, version info bellow:

Google Chrome	34.0.1847.137 (Official Build 268882) 
OS	Mac OS X 
Blink	537.36 (@173057)
JavaScript	V8 3.24.35.33
Flash	13.0.0.214
User Agent	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/34.0.1847.137 Safari/537.36

**Comment by mmahalwy** [comment]
what happened to this?

**Comment by LeviBotelho** [comment]
I thought I fixed it. Experiencing the problem?
